Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE
  AppName:
    Type: String
    Default: payment-failure-comms

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Mappings:
  StageMap:
    PROD:
      Schedule: 'rate(30 minutes)'
      IdapiInstanceUrl: idapi.theguardian.com
      IdapiStage: PROD
      IdapiSecretsVersion: 190ff297-e512-4c87-a88b-015f863f8285
      BrazeInstanceUrl: rest.fra-01.braze.eu
      BrazeAppGroup: DEV
      BrazeSecretsVersion: 454bfb7f-ea8f-4870-be4b-a7068d2e16f4
    CODE:
      Schedule: 'rate(365 days)'
      IdapiInstanceUrl: idapi.code.dev-theguardian.com
      IdapiStage: CODE
      IdapiSecretsVersion: 4349b3d1-5dc4-4a44-bded-263fff6dbdaa
      BrazeInstanceUrl: rest.fra-01.braze.eu
      BrazeAppGroup: DEV
      BrazeSecretsVersion: 454bfb7f-ea8f-4870-be4b-a7068d2e16f4
    DEV:
      Schedule: 'rate(365 days)'
      IdapiInstanceUrl: idapi.code.dev-theguardian.com
      IdapiStage: CODE
      IdapiSecretsVersion: 4349b3d1-5dc4-4a44-bded-263fff6dbdaa
      BrazeInstanceUrl: rest.fra-01.braze.eu
      BrazeAppGroup: DEV
      BrazeSecretsVersion: 454bfb7f-ea8f-4870-be4b-a7068d2e16f4

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AppName}-${Stage}
      RetentionInDays: 14

  PaymentFailureCommsLambda:
    Type: AWS::Serverless::Function
    DependsOn: LogGroup
    Properties:
      FunctionName: !Sub ${AppName}-${Stage}
      Handler: payment_failure_comms.Handler::handleRequest
      Runtime: java8.al2
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/${AppName}/${AppName}.jar
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          idapiInstanceUrl: !FindInMap [ StageMap, !Ref Stage, IdapiInstanceUrl ]
          idapiBearerToken: !Sub
            - '{{resolve:secretsmanager:IDAPI/${IDAPIStage}/${AppName}:SecretString:bearerToken::${IDAPISecretsVersion}}}'
            - IdapiStage: !FindInMap [ StageMap, !Ref Stage, IdapiStage ]
              IdapiSecretsVersion: !FindInMap [ StageMap, !Ref Stage, IdapiSecretsVersion ]
          brazeInstanceUrl: !FindInMap [ StageMap, !Ref Stage, BrazeInstanceUrl ]
          brazeBearerToken:
            !Sub
            - '{{resolve:secretsmanager:Braze/${BrazeAppGroup}/${AppName}:SecretString:bearerToken::${BrazeSecretsVersion}}}'
            - BrazeAppGroup: !FindInMap [ StageMap, !Ref Stage, BrazeAppGroup ]
              BrazeSecretsVersion: !FindInMap [ StageMap, !Ref Stage, BrazeSecretsVersion ]
          zuoraAppIdForBraze:
            !Sub
            - '{{resolve:secretsmanager:Braze/${BrazeAppGroup}/${AppName}:SecretString:zuoraAppId::${BrazeSecretsVersion}}}'
            - BrazeAppGroup: !FindInMap [ StageMap, !Ref Stage, BrazeAppGroup ]
              BrazeSecretsVersion: !FindInMap [ StageMap, !Ref Stage, BrazeSecretsVersion ]
      Events:
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: !FindInMap [ StageMap, !Ref Stage, Schedule ]
            Description: Runs Soft Opt-In Consent Setter
            Enabled: False
