name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:

    if: github.actor != 'scala-steward'

    runs-on: ubuntu-latest

    # Required by aws-actions/configure-aws-credentials
    permissions:
      id-token: write
      contents: read

    steps:
    
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
        
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore and save dependency cache
        uses: coursier/cache-action@v6

        # Required by sbt riffRaffUpload
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Run SBT tasks
        run: >
          sbt
          clean
          scalafmtCheckAll
          scalafmtSbtCheck
          riffRaffUpload
